import 'package:choose_bank/app_bar.dart';
import 'package:choose_bank/choose_bank.dart';
import 'package:choose_bank/name_bank.dart';
import 'package:flutter/material.dart';

class InformationBank extends StatefulWidget {
  const InformationBank({Key? key}) : super(key: key);

  @override
  _InformationBankState createState() => _InformationBankState();
}

class _InformationBankState extends State<InformationBank> {
   List<namebank> listBank = [
     namebank(bank: "NHTMCP Ky thuong VN (Texhcombank)"),
     namebank(bank: "NH Chinh sach xa hoi (VBSP)"),
     namebank(bank: "NH Cong thuong VN (Vietinbank)"),
     namebank(bank: "NH Dau tu va phat trien VN (BIDV)"),
     namebank(bank: "NH NNo&Pt Nong thon VN-Agribank "),
     namebank(bank: "NH Phat trien Viet Nam (VDB)"),
     namebank(bank: "Ngan hang TMCP Ngoai thuong Viet Nam"),
     namebank(bank: "NH BAO VIET (Bao Viet Bank)"),
     namebank(bank: "NH Tien Phong (Tien Phong Bank)"),
     namebank(bank: "NH TM TNHH MTV Xay Dung VN (CB Bank)"),
     namebank(bank: "NH TMCP Ban Viet "),
     namebank(bank: "NH TMCP BUU DIEN LEIN VIET "),
     namebank(bank: "NH TMCP Dai Chung (PVcombank)"),
     namebank(bank: "NH TMCP Quoc Dan (Nam Viet cu)"),
     namebank(bank: "NH TMCP Viet A"),
     namebank(bank: "NH TMCP Viet Nam Thuong Tin (Vietbank)"),
     namebank(bank: "NHTMCP A Chau (ACB)"),
     namebank(bank: "NHTMCP An Binh (ABBank)"),
     namebank(bank: "NHTMCP Bac A (Bac A bank)"),
     namebank(bank: "NHTMCP Dai Duong (Oceanbank)"),
     namebank(bank: "NHTMCP Dau khi Toan cau (GPBank)"),
     namebank(bank: "NHTMCP Dong A (Dong A bank)"),
     namebank(bank: "NHTMCP Dong Nam A (Seabank)"),
     namebank(bank: "NHTMCP Hang Hai (Dong A bank)"),
     namebank(bank: "NHTMCP Kien Long (Kien Long bank)"),
     namebank(bank: "NHTMCP Nam A (Nam A bank)"),
     namebank(bank: "NHTMCP phat trien Tp HCM (HD bank)"),
     namebank(bank: "NHTMCP Phuong Dong (OCB)"),
     namebank(bank: "NHTMCP Quan Doi (MB)"),
     namebank(bank: "NHTMCP Quoc Te (VIB)"),
     namebank(bank: "NHTMCP Sai Gon (SCB)"),
     namebank(bank: "NHTMCP Sai gon - Ha Noi (SHB)"),
     namebank(bank: "NHTMCP Sai gon Thuong Tin  (Sacombank)"),
     namebank(bank: "NHTMCP SG Cong Thuong (SaigonBank)"),
     namebank(bank: "NHTMCP VN Thinh Vuong (VP Bank)"),
     namebank(bank: "NHTMCP Xang dau Petrolimex (PGBank)"),
     namebank(bank: "NHTMCP Xuat Nhap Khau (Eximbank)"),
     namebank(bank: "INDOVINA BANK"),
     namebank(bank: "NH lien doanh Viet Nga"),
     namebank(bank: "NH lien doanh Viet Thai"),
     namebank(bank: "PUBLIC BANK VN"),
     namebank(bank: "Agricultural Bank of China Ltd (ABOC)"),
     namebank(bank: "ANZ BANK"),
     namebank(bank: "BANGKOK BANK"),
     namebank(bank: "BANK OF CHINA"),
     namebank(bank: "Bank of Communications"),
     namebank(bank: "Bank of India"),
     namebank(bank: "BNP Paribas Chi nhanh HN"),
     namebank(bank: "BNP- PARIBAS CN HCM"),
     namebank(bank: "BPCE IOM"),
     namebank(bank: "China Construction Bank Corporation"),
     namebank(bank: "CIMB BANK"),
     namebank(bank: "CITI BANK"),
     namebank(bank: "CITI BANK HN "),
     namebank(bank: "Credit Agricole CIB"),
     namebank(bank: "DEUTSCHE BANK"),
     namebank(bank: "FIRST COMMERCIAL BANK HCM"),
     namebank(bank: "HONGKONG AND SHANGHAI BANK (HSBC)"),
     namebank(bank: "HUANAN COMMERCIAL BANK LTD Chi nhanh SG"),
     namebank(bank: "Industrial Bank of korea"),
     namebank(bank: "JP MORGAN CHASE BANK"),
     namebank(bank: "KEB HANA BANK"),
     namebank(bank: "MALAYAN BANKING BERHAD HCM"),
     namebank(bank: "MAY BANK (HN)"),
     namebank(bank: "MEGA INTERNATIONAL COMMERCIAL Co.LTD"),
     namebank(bank: "Mizuho Corpotate Bank Ltd.,Hn"),
     namebank(bank: "MIZUHO CORPORATE BANK,LTD"),
     namebank(bank: "Ngan hang Busan"),
     namebank(bank: "Ngan hang MUFG Bank, LTD CN HN"),
     namebank(bank: "NH Hana"),
     namebank(bank: "NH CATHAY UNITED"),
     namebank(bank: "NH Cong nghiep Han Quoc"),
     namebank(bank: "NH DBS Bank Ltd CN HCM"),
     namebank(bank: "NH DTPT Campuchia Ha Noi"),
     namebank(bank: "NH DTPT Campuchia - HCM"),
     namebank(bank: "NH FAR EAST NATIONAL BANK"),
     namebank(bank: "NH FIRS COMMERCIAL BANK HANOI"),
     namebank(bank: "NH Industrial & Commercial Bank of China"),
     namebank(bank: "NH Kookmin TP Ho Chi Minh"),
     namebank(bank: "NH MUFG BANK, LTD CN HCM "),
     namebank(bank: "NH NongHyup"),
     namebank(bank: "NH Taipei FubonC.B"),
     namebank(bank: "NH TM Taipei Fubon"),
     namebank(bank: "NH TM TNHH E.Sun"),
     namebank(bank: "NH TNHH CTBC (NHTM Chinatrust)"),
     namebank(bank: "NH TNHH MTV Shinhan VN"),
     namebank(bank: "NH TNHH UOB VIETNAM"),
     namebank(bank: "NHTM Taipei Fubon"),
     namebank(bank: "NHTNHH MTV Hong Leong VN"),
     namebank(bank: "NH OVERSEA- CHINESE BANKING CORP Ltd"),
     namebank(bank: "Siam Commercial Bank Public Company Ltd"),
     namebank(bank: "STANDARD CHARTERED BANK"),
     namebank(bank: "SUMITOMO MITSUI BANKING CORPORATION"),
     namebank(bank: "The Shanghai Com&Savings Bank"),
     namebank(bank: "UOB CN HCM"),
     namebank(bank: "Woori Bank Viet Nam"),
   ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar:const WidgetAppBar(),
      body: ChooseBank(listBank: listBank),
    );
  }
}

